language: php

sudo: required

php:
  - '5.6'

before_script:
    - sudo apt-get update
    - sudo apt-get install apache2
    - sudo service apache2 restart
    - sudo apt-get install php5-mysql
    #- sudo apt-get install pdo-mysql php5-mysql
    - sudo service apache2 restart
    - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password password'
    - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password password'
    - sudo apt-get -y install mysql-server
    - cd $HOME
    - cd ..
    - cd ..
    - ls -la
    - pwd
    - cd var
    - ls -la
    - cd www
    - ls -la
    - cd html
    - ls -la
    - pwd



script:

env:
  matrix:
  - BROWSER=firefox

after_script:

addons:
  artifacts:
    bucket: "kolpakova-s3"
    endpoint: "https://kolpakova-s3.s3-eu-central-1.amazonaws.com/"
    s3_region: "eu-central-1"
