language: php, java

sudo: required

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'


before_script:
    - sudo apt-get update
    - sudo apt-get install apache2
    - sudo service apache2 restart



script:

env:
  matrix:
  - BROWSER=firefox

after_script:

addons:
  artifacts:
    bucket: "kolpakova-s3"
    endpoint: "https://kolpakova-s3.s3-eu-central-1.amazonaws.com/"
    s3_region: "eu-central-1"
