language: php

sudo: required

php:
  - '5.6'



before_script:
    - sudo apt-get update
    - sudo apt-get install apache2
    - sudo service apache2 restart
    - sudo apt-get install php5-mysql
    - sudo service apache2 restart
    - ls -la
    - cd ..
    - ls -la
    - cd ..
    - ls -la
    - cd ..
    - ls -la



script:

env:
  matrix:
  - BROWSER=firefox

after_script:

addons:
  artifacts:
    bucket: "kolpakova-s3"
    endpoint: "https://kolpakova-s3.s3-eu-central-1.amazonaws.com/"
    s3_region: "eu-central-1"
